#!/bin/bash
#SBATCH -J flex
#SBATCH -o %j.out
#SBATCH -p parallel-12
#SBATCH -n 1
#SBATCH -t 5-00:00:00


scontrol show hostnames "$SLURM_JOB_NODELIST" > hostfile
STARTTIME=$(date +%Y-%m-%d%t%k:%M:%S:%N)
 
 ./run -g -o


ENDTIME=$(date +%Y-%m-%d%t%k:%M:%S:%N)
echo -e "$SLURM_JOB_ID\t $SLURM_JOB_NAME\t $STARTTIME\t $ENDTIME" >> ./brick.out